import type { CompanyTag, Difficulty, Topic } from '../../types/question'

export const TOPICS: Topic[] = [
  'arrays',
  'strings',
  'hashing',
  'linked-lists',
  'stacks',
  'queues',
  'trees',
  'bst',
  'heaps',
  'graphs',
  'dp',
  'greedy',
  'backtracking',
  'recursion',
  'binary-search',
  'sliding-window',
  'two-pointers',
  'bit-manipulation',
  'tries',
  'segment-trees',
  'system-design',
  'sql',
  'os',
  'dbms',
  'oop',
  'networking',
]

export const COMPANIES: CompanyTag[] = [
  'Google',
  'Meta',
  'Amazon',
  'Apple',
  'Microsoft',
  'Uber',
  'Netflix',
  'Flipkart',
  'General',
]

export const DIFFICULTIES: Difficulty[] = ['easy', 'medium', 'hard']

export const TOPIC_LABEL: Record<Topic, string> = {
  arrays: 'Arrays',
  strings: 'Strings',
  hashing: 'Hashing',
  'linked-lists': 'Linked Lists',
  stacks: 'Stacks',
  queues: 'Queues',
  trees: 'Trees',
  bst: 'Binary Search Trees',
  heaps: 'Heaps',
  graphs: 'Graphs',
  dp: 'Dynamic Programming',
  greedy: 'Greedy',
  backtracking: 'Backtracking',
  recursion: 'Recursion',
  'binary-search': 'Binary Search',
  'sliding-window': 'Sliding Window',
  'two-pointers': 'Two Pointers',
  'bit-manipulation': 'Bit Manipulation',
  tries: 'Tries',
  'segment-trees': 'Segment Trees',
  'system-design': 'System Design',
  sql: 'SQL',
  os: 'Operating Systems',
  dbms: 'DBMS',
  oop: 'OOP',
  networking: 'Networking',
}
