#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$HOME/.local/bin"
AUTO="$HOME/.config/autostart"
mkdir -p "$BIN" "$AUTO" "$HOME/.config/prepdesk"

chmod +x \
  "$ROOT/desktop/native_lock.py" \
  "$ROOT/desktop/prepdesk-lock" \
  "$ROOT/desktop/show-bypass.sh" \
  "$ROOT/desktop/lock_shell.py"

ln -sfn "$ROOT/desktop/prepdesk-lock" "$BIN/prepdesk-lock"
ln -sfn "$ROOT/desktop/show-bypass.sh" "$BIN/prepdesk-show-bypass"
ln -sfn "$ROOT/desktop/rotate-bypass.sh" "$BIN/prepdesk-rotate-bypass"

# Restore keybinds on login if a previous lock crashed (runs before lock)
cat > "$AUTO/prepdesk-restore-keys.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=PrepDesk Restore Keys
Comment=Restore GNOME shortcuts if PrepDesk Lock crashed
Exec=/usr/bin/python3 $ROOT/desktop/keybinds.py restore
Terminal=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=1
EOF

# Ensure / rotate to a ~73-char 2-UUID bypass key
cd "$ROOT"
node -e "
const fs=require('fs');const os=require('os');const path=require('path');const {randomUUID}=require('crypto');
const dir=path.join(os.homedir(),'.config','prepdesk');
fs.mkdirSync(dir,{recursive:true});
const f=path.join(dir,'bypass.key');
const cur=fs.existsSync(f)?fs.readFileSync(f,'utf8').trim():'';
if(!cur || cur.length < 70 || cur.length > 80){
  const key=randomUUID()+'-'+randomUUID();
  fs.writeFileSync(f,key+'\n',{mode:0o600});
  console.log('Generated bypass key ('+key.length+' chars).');
} else {
  console.log('Bypass file:', f);
  console.log('Length:', cur.length);
}
"

cat > "$AUTO/prepdesk-lock.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=PrepDesk Lock
Comment=Solve one interview question to unlock your desktop
Exec=$BIN/prepdesk-lock
Icon=utilities-terminal
Terminal=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=3
StartupNotify=false
EOF

echo
echo "Installing retest timer (checks every 15 minutes)…"
SYSTEMD_USER="${HOME}/.config/systemd/user"
mkdir -p "${SYSTEMD_USER}"
cat > "${SYSTEMD_USER}/prepdesk-retest.service" <<EOF
[Unit]
Description=PrepDesk retest launcher

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 ${ROOT}/desktop/retest-check.py
EOF
cat > "${SYSTEMD_USER}/prepdesk-retest.timer" <<EOF
[Unit]
Description=PrepDesk retest check every 15 minutes

[Timer]
OnBootSec=5min
OnUnitActiveSec=15min
Persistent=true

[Install]
WantedBy=timers.target
EOF
systemctl --user daemon-reload 2>/dev/null || true
systemctl --user enable --now prepdesk-retest.timer 2>/dev/null || echo "(systemd user timer not enabled — run manually later)"

echo
echo "Installed PrepDesk Lock"
echo "  Autostart: $AUTO/prepdesk-lock.desktop"
echo "  Command:   prepdesk-lock"
echo "  Bypass:    prepdesk-show-bypass   (TTY/Ctrl+Alt+F3 if stuck)"
echo "  Key file:  ~/.config/prepdesk/bypass.key"
echo "  Retest:    prepdesk-retest.timer (if systemd user available)"
echo
echo "IMPORTANT: write down the bypass key before next login:"
echo "  prepdesk-show-bypass"
echo
echo "Native GTK lock grabs keyboard+mouse when possible; gsettings disables Alt+Tab/Super/logout until unlock."
echo "Hard power-button shutdown is NOT blocked."
echo
echo "Test now:  prepdesk-lock"
echo "Uninstall: ${ROOT}/desktop/uninstall-lock.sh"
